const verses = {
  "01-01": { ref: "Genesis 1:1", text: "In the beginning God created the heaven and the earth." },
  "01-02": { ref: "1 Peter 2:1", text: "Wherefore laying aside all malice, and all guile, and hypocrisies, and envies, and all evil speakings," },
  "01-03": { ref: "Romans 3:1", text: "What advantage then hath the Jew? or what profit is there of circumcision?" },
  "01-04": { ref: "1 John 4:1", text: "Beloved, believe not every spirit, but try the spirits whether they are of God..." },
  "01-05": { ref: "Romans 5:1", text: "Therefore being justified by faith, we have peace with God through our Lord Jesus Christ:" },
  "01-06": { ref: "John 6:1", text: "After these things Jesus went over the sea of Galilee, which is the sea of Tiberias." },
  "01-07": { ref: "Matthew 7:1", text: "Judge not, that ye be not judged." },
  "01-08": { ref: "Romans 8:1", text: "There is therefore now no condemnation to them which are in Christ Jesus..." },
  "01-09": { ref: "Proverbs 9:1", text: "Wisdom hath builded her house, she hath hewn out her seven pillars:" },
  "01-10": { ref: "Romans 10:1", text: "Brethren, my heart's desire and prayer to God for Israel is, that they might be saved." },
  "01-11": { ref: "Hebrews 11:1", text: "Now faith is the substance of things hoped for, the evidence of things not seen." },
  "01-12": { ref: "Romans 12:1", text: "I beseech you therefore, brethren, by the mercies of God..." },
  "01-13": { ref: "1 Corinthians 13:1", text: "Though I speak with the tongues of men and of angels, and have not charity..." },
  "01-14": { ref: "John 14:1", text: "Let not your heart be troubled: ye believe in God, believe also in me." },
  "01-15": { ref: "1 Corinthians 15:1", text: "Moreover, brethren, I declare unto you the gospel which I preached unto you..." },
  "01-16": { ref: "John 3:16", text: "For God so loved the world, that he gave his only begotten Son..." },
  "01-17": { ref: "Proverbs 17:1", text: "Better is a dry morsel, and quietness therewith, than an house full of sacrifices with strife." },
  "01-18": { ref: "Luke 18:1", text: "And he spake a parable unto them to this end, that men ought always to pray, and not to faint;" },
  "01-19": { ref: "Psalm 19:1", text: "The heavens declare the glory of God; and the firmament sheweth his handywork." },
  "01-20": { ref: "Exodus 20:1", text: "And God spake all these words, saying," },
  "01-21": { ref: "Matthew 21:1", text: "And when they drew nigh unto Jerusalem... then sent Jesus two disciples," },
  "01-22": { ref: "Proverbs 22:1", text: "A good name is rather to be chosen than great riches..." },
  "01-23": { ref: "Psalm 23:1", text: "The LORD is my shepherd; I shall not want." },
  "01-24": { ref: "Joshua 24:1", text: "And Joshua gathered all the tribes of Israel to Shechem..." },
  "01-25": { ref: "Matthew 25:1", text: "Then shall the kingdom of heaven be likened unto ten virgins..." },
  "01-26": { ref: "Isaiah 26:1", text: "In that day shall this song be sung in the land of Judah..." },
  "01-27": { ref: "Proverbs 27:1", text: "Boast not thyself of to morrow; for thou knowest not what a day may bring forth." },
  "01-28": { ref: "Deuteronomy 28:1", text: "And it shall come to pass, if thou shalt hearken diligently unto the voice of the LORD thy God..." },
  "01-29": { ref: "Jeremiah 29:1", text: "Now these are the words of the letter that Jeremiah the prophet sent from Jerusalem..." },
  "01-30": { ref: "Job 30:1", text: "But now they that are younger than I have me in derision..." },
  "01-31": { ref: "Proverbs 31:1", text: "The words of king Lemuel, the prophecy that his mother taught him." },
  // ... continue with all other dates ...
  "02-29": { ref: "Matthew 9:2", text: "Son, be of good cheer; thy sins be forgiven thee." },
  "03-01": { ref: "Ecclesiastes 1:3", text: "What profit hath a man of all his labour which he taketh under the sun?" },
"03-02": { ref: "Philippians 2:3", text: "Let nothing be done through strife or vainglory; but in lowliness of mind let each esteem other better than themselves." },
"03-03": { ref: "Amos 3:3", text: "Can two walk together, except they be agreed?" },
"03-04": { ref: "Colossians 3:4", text: "When Christ, who is our life, shall appear, then shall ye also appear with him in glory." },
"03-05": { ref: "Proverbs 3:5", text: "Trust in the LORD with all thine heart; and lean not unto thine own understanding." },
"03-06": { ref: "Proverbs 6:3", text: "Do this now, my son, and deliver thyself, when thou art come into the hand of thy friend..." },
"03-07": { ref: "Matthew 7:3", text: "And why beholdest thou the mote that is in thy brother's eye..." },
"03-08": { ref: "Romans 8:3", text: "For what the law could not do, in that it was weak through the flesh..." },
"03-09": { ref: "Proverbs 9:3", text: "She hath sent forth her maidens: she crieth upon the highest places of the city," },
"03-10": { ref: "Romans 10:3", text: "For they being ignorant of God's righteousness, and going about to establish their own righteousness..." },
"03-11": { ref: "Hebrews 11:3", text: "Through faith we understand that the worlds were framed by the word of God..." },
"03-12": { ref: "Romans 12:3", text: "For I say... to every man that is among you... not to think of himself more highly than he ought to think;" },
"03-13": { ref: "1 Corinthians 13:3", text: "And though I bestow all my goods to feed the poor... and have not charity, it profiteth me nothing." },
"03-14": { ref: "John 14:3", text: "And if I go and prepare a place for you, I will come again, and receive you unto myself..." },
"03-15": { ref: "1 Corinthians 15:3", text: "For I delivered unto you first of all that which I also received, how that Christ died for our sins..." },
"03-16": { ref: "John 3:16", text: "For God so loved the world, that he gave his only begotten Son..." },
"03-17": { ref: "Proverbs 17:3", text: "The fining pot is for silver, and the furnace for gold: but the LORD trieth the hearts." },
"03-18": { ref: "Luke 18:3", text: "And there was a widow in that city; and she came unto him, saying, Avenge me of mine adversary." },
"03-19": { ref: "Psalm 19:3", text: "There is no speech nor language, where their voice is not heard." },
"03-20": { ref: "Exodus 20:3", text: "Thou shalt have no other gods before me." },
"03-21": { ref: "Matthew 21:3", text: "And if any man say ought unto you, ye shall say, The Lord hath need of them..." },
"03-22": { ref: "Proverbs 22:3", text: "A prudent man foreseeth the evil, and hideth himself: but the simple pass on, and are punished." },
"03-23": { ref: "Psalm 23:3", text: "He restoreth my soul: he leadeth me in the paths of righteousness for his name's sake." },
"03-24": { ref: "Joshua 24:3", text: "And I took your father Abraham from the other side of the flood..." },
"03-25": { ref: "Matthew 25:3", text: "They that were foolish took their lamps, and took no oil with them:" },
"03-26": { ref: "Isaiah 26:3", text: "Thou wilt keep him in perfect peace, whose mind is stayed on thee..." },
"03-27": { ref: "Proverbs 27:3", text: "A stone is heavy, and the sand weighty; but a fool's wrath is heavier than them both." },
"03-28": { ref: "Deuteronomy 28:3", text: "Blessed shalt thou be in the city, and blessed shalt thou be in the field." },
"03-29": { ref: "Jeremiah 29:3", text: "By the hand of Elasah the son of Shaphan..." },
"03-30": { ref: "Job 30:3", text: "For want and famine they were solitary; fleeing into the wilderness..." },
"03-31": { ref: "Proverbs 31:3", text: "Give not thy strength unto women, nor thy ways to that which destroyeth kings." },
"04-01": { ref: "Philippians 4:1", text: "Therefore, my brethren dearly beloved and longed for, my joy and crown, so stand fast in the Lord..." },
"04-02": { ref: "Philippians 2:4", text: "Look not every man on his own things, but every man also on the things of others." },
"04-03": { ref: "Colossians 3:4", text: "When Christ, who is our life, shall appear, then shall ye also appear with him in glory." },
"04-04": { ref: "Philippians 4:4", text: "Rejoice in the Lord alway: and again I say, Rejoice." },
"04-05": { ref: "Philippians 4:5", text: "Let your moderation be known unto all men. The Lord is at hand." },
"04-06": { ref: "Philippians 4:6", text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving..." },
"04-07": { ref: "Philippians 4:7", text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds..." },
"04-08": { ref: "Philippians 4:8", text: "Whatsoever things are true, whatsoever things are honest... think on these things." },
"04-09": { ref: "Philippians 4:9", text: "Those things, which ye have both learned, and received, and heard, and seen in me, do..." },
"04-10": { ref: "Romans 10:4", text: "For Christ is the end of the law for righteousness to every one that believeth." },
"04-11": { ref: "Hebrews 11:4", text: "By faith Abel offered unto God a more excellent sacrifice than Cain..." },
"04-12": { ref: "Romans 12:4", text: "For as we have many members in one body, and all members have not the same office:" },
"04-13": { ref: "1 Corinthians 13:4", text: "Charity suffereth long, and is kind; charity envieth not..." },
"04-14": { ref: "John 14:4", text: "And whither I go ye know, and the way ye know." },
"04-15": { ref: "1 Corinthians 15:4", text: "And that he was buried, and that he rose again the third day according to the scriptures:" },
"04-16": { ref: "John 16:4", text: "But these things have I told you, that when the time shall come, ye may remember..." },
"04-17": { ref: "Proverbs 17:4", text: "A wicked doer giveth heed to false lips; and a liar giveth ear to a naughty tongue." },
"04-18": { ref: "Luke 18:4", text: "And he would not for a while: but afterward he said within himself, Though I fear not God..." },
"04-19": { ref: "Psalm 19:4", text: "Their line is gone out through all the earth, and their words to the end of the world..." },
"04-20": { ref: "Exodus 20:4", text: "Thou shalt not make unto thee any graven image..." },
"04-21": { ref: "Matthew 21:4", text: "All this was done, that it might be fulfilled which was spoken by the prophet..." },
"04-22": { ref: "Proverbs 22:4", text: "By humility and the fear of the LORD are riches, and honour, and life." },
"04-23": { ref: "Psalm 23:4", text: "Yea, though I walk through the valley of the shadow of death, I will fear no evil..." },
"04-24": { ref: "Joshua 24:4", text: "And I gave unto Isaac Jacob and Esau..." },
"04-25": { ref: "Matthew 25:4", text: "But the wise took oil in their vessels with their lamps." },
"04-26": { ref: "Isaiah 26:4", text: "Trust ye in the LORD for ever: for in the LORD JEHOVAH is everlasting strength:" },
"04-27": { ref: "Proverbs 27:4", text: "Wrath is cruel, and anger is outrageous; but who is able to stand before envy?" },
"04-28": { ref: "Deuteronomy 28:4", text: "Blessed shall be the fruit of thy body, and the fruit of thy ground..." },
"04-29": { ref: "Jeremiah 29:4", text: "Thus saith the LORD of hosts, the God of Israel, unto all that are carried away captives..." },
"04-30": { ref: "Job 30:4", text: "Who cut up mallows by the bushes, and juniper roots for their meat." },
"05-01": { ref: "1 Peter 5:1", text: "The elders which are among you I exhort, who am also an elder..." },
"05-02": { ref: "Exodus 5:2", text: "And Pharaoh said, Who is the Lord, that I should obey his voice to let Israel go?" },
"05-03": { ref: "Amos 5:3", text: "For thus saith the Lord God; The city that went out by a thousand shall leave an hundred..." },
"05-04": { ref: "Philippians 4:5", text: "Let your moderation be known unto all men. The Lord is at hand." },
"05-05": { ref: "Romans 5:5", text: "And hope maketh not ashamed; because the love of God is shed abroad in our hearts..." },
"05-06": { ref: "Galatians 6:5", text: "For every man shall bear his own burden." },
"05-07": { ref: "1 John 2:7", text: "Brethren, I write no new commandment unto you, but an old commandment which ye had from the beginning." },
"05-08": { ref: "Ephesians 2:8", text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:" },
"05-09": { ref: "1 Samuel 2:9", text: "He will keep the feet of his saints, and the wicked shall be silent in darkness..." },
"05-10": { ref: "Titus 2:10", text: "Not purloining, but shewing all good fidelity; that they may adorn the doctrine of God our Saviour in all things." },
"05-11": { ref: "Ephesians 2:11", text: "Wherefore remember, that ye being in time past Gentiles in the flesh..." },
"05-12": { ref: "1 Peter 2:12", text: "Having your conversation honest among the Gentiles..." },
"05-13": { ref: "Ephesians 2:13", text: "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ." },
"05-14": { ref: "1 Corinthians 13:5", text: "Charity doth not behave itself unseemly, seeketh not her own..." },
"05-15": { ref: "Luke 2:15", text: "And it came to pass, as the angels were gone away from them into heaven..." },
"05-16": { ref: "2 Timothy 3:16", text: "All scripture is given by inspiration of God, and is profitable for doctrine..." },
"05-17": { ref: "Proverbs 17:5", text: "Whoso mocketh the poor reproacheth his Maker..." },
"05-18": { ref: "Proverbs 18:5", text: "It is not good to accept the person of the wicked, to overthrow the righteous in judgment." },
"05-19": { ref: "Proverbs 19:5", text: "A false witness shall not be unpunished, and he that speaketh lies shall not escape." },
"05-20": { ref: "Exodus 20:5", text: "Thou shalt not bow down thyself to them, nor serve them..." },
"05-21": { ref: "Matthew 21:5", text: "Tell ye the daughter of Sion, Behold, thy King cometh unto thee..." },
"05-22": { ref: "Proverbs 22:5", text: "Thorns and snares are in the way of the froward..." },
"05-23": { ref: "Psalm 23:5", text: "Thou preparest a table before me in the presence of mine enemies..." },
"05-24": { ref: "Joshua 24:5", text: "I sent Moses also and Aaron, and I plagued Egypt..." },
"05-25": { ref: "Matthew 25:5", text: "While the bridegroom tarried, they all slumbered and slept." },
"05-26": { ref: "Isaiah 26:5", text: "For he bringeth down them that dwell on high..." },
"05-27": { ref: "Proverbs 27:5", text: "Open rebuke is better than secret love." },
"05-28": { ref: "Deuteronomy 28:5", text: "Blessed shall be thy basket and thy store." },
"05-29": { ref: "Jeremiah 29:5", text: "Build ye houses, and dwell in them; and plant gardens, and eat the fruit of them;" },
"05-30": { ref: "Job 30:5", text: "They were driven forth from among men, (they cried after them as after a thief;)" },
"05-31": { ref: "Proverbs 31:5", text: "Lest they drink, and forget the law, and pervert the judgment of any of the afflicted." },"06-01": { ref: "1 Peter 5:6", text: "Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time:" },
"06-02": { ref: "Exodus 5:6", text: "And Pharaoh commanded the same day the taskmasters of the people..." },
"06-03": { ref: "Amos 5:6", text: "Seek the Lord, and ye shall live; lest he break out like fire in the house of Joseph..." },
"06-04": { ref: "Philippians 4:6", text: "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God." },
"06-05": { ref: "Romans 5:6", text: "For when we were yet without strength, in due time Christ died for the ungodly." },
"06-06": { ref: "Galatians 6:6", text: "Let him that is taught in the word communicate unto him that teacheth in all good things." },
"06-07": { ref: "1 John 2:7", text: "Brethren, I write no new commandment unto you, but an old commandment which ye had from the beginning." },
"06-08": { ref: "Ephesians 2:8", text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:" },
"06-09": { ref: "1 Samuel 2:9", text: "He will keep the feet of his saints, and the wicked shall be silent in darkness..." },
"06-10": { ref: "Titus 2:10", text: "Not purloining, but shewing all good fidelity; that they may adorn the doctrine of God our Saviour in all things." },
"06-11": { ref: "Ephesians 2:11", text: "Wherefore remember, that ye being in time past Gentiles in the flesh..." },
"06-12": { ref: "1 Peter 2:12", text: "Having your conversation honest among the Gentiles..." },
"06-13": { ref: "Ephesians 2:13", text: "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ." },
"06-14": { ref: "1 Corinthians 13:6", text: "Rejoiceth not in iniquity, but rejoiceth in the truth;" },
"06-15": { ref: "Luke 2:15", text: "And it came to pass, as the angels were gone away from them into heaven..." },
"06-16": { ref: "2 Timothy 3:16", text: "All scripture is given by inspiration of God, and is profitable for doctrine..." },
"06-17": { ref: "Proverbs 17:6", text: "Children’s children are the crown of old men; and the glory of children are their fathers." },
"06-18": { ref: "Proverbs 18:6", text: "A fool’s lips enter into contention, and his mouth calleth for strokes." },
"06-19": { ref: "Proverbs 19:6", text: "Many will intreat the favour of the prince: and every man is a friend to him that giveth gifts." },
"06-20": { ref: "Exodus 20:6", text: "And shewing mercy unto thousands of them that love me, and keep my commandments." },
"06-21": { ref: "Matthew 21:6", text: "And the disciples went, and did as Jesus commanded them," },
"06-22": { ref: "Proverbs 22:6", text: "Train up a child in the way he should go: and when he is old, he will not depart from it." },
"06-23": { ref: "Psalm 23:6", text: "Surely goodness and mercy shall follow me all the days of my life..." },
"06-24": { ref: "Joshua 24:6", text: "And I brought your fathers out of Egypt: and ye came unto the sea..." },
"06-25": { ref: "Matthew 25:6", text: "And at midnight there was a cry made, Behold, the bridegroom cometh; go ye out to meet him." },
"06-26": { ref: "Isaiah 26:6", text: "The foot shall tread it down, even the feet of the poor, and the steps of the needy." },
"06-27": { ref: "Proverbs 27:6", text: "Faithful are the wounds of a friend; but the kisses of an enemy are deceitful." },
"06-28": { ref: "Deuteronomy 28:6", text: "Blessed shalt thou be when thou comest in, and blessed shalt thou be when thou goest out." },
"06-29": { ref: "Jeremiah 29:6", text: "Take ye wives, and beget sons and daughters..." },
"06-30": { ref: "Job 30:6", text: "To dwell in the cliffs of the valleys, in caves of the earth, and in the rocks." },
"07-01": { ref: "1 Peter 5:7", text: "Casting all your care upon him; for he careth for you." },
"07-02": { ref: "Exodus 5:7", text: "Ye shall no more give the people straw to make brick, as heretofore..." },
"07-03": { ref: "Amos 5:7", text: "Ye who turn judgment to wormwood, and leave off righteousness in the earth," },
"07-04": { ref: "Philippians 4:7", text: "And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus." },
"07-05": { ref: "Romans 5:7", text: "For scarcely for a righteous man will one die..." },
"07-06": { ref: "Galatians 6:7", text: "Be not deceived; God is not mocked: for whatsoever a man soweth, that shall he also reap." },
"07-07": { ref: "1 John 2:7", text: "Brethren, I write no new commandment unto you..." },
"07-08": { ref: "Ephesians 2:8", text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:" },
"07-09": { ref: "1 Samuel 2:9", text: "He will keep the feet of his saints, and the wicked shall be silent in darkness..." },
"07-10": { ref: "Titus 2:10", text: "Not purloining, but shewing all good fidelity..." },
"07-11": { ref: "Ephesians 2:11", text: "Wherefore remember, that ye being in time past Gentiles in the flesh..." },
"07-12": { ref: "1 Peter 2:12", text: "Having your conversation honest among the Gentiles..." },
"07-13": { ref: "Ephesians 2:13", text: "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ." },
"07-14": { ref: "1 Corinthians 13:7", text: "Beareth all things, believeth all things, hopeth all things, endureth all things." },
"07-15": { ref: "Luke 2:15", text: "And it came to pass, as the angels were gone away from them into heaven..." },
"07-16": { ref: "2 Timothy 3:16", text: "All scripture is given by inspiration of God, and is profitable for doctrine..." },
"07-17": { ref: "Proverbs 17:7", text: "Excellent speech becometh not a fool: much less do lying lips a prince." },
"07-18": { ref: "Proverbs 18:7", text: "A fool’s mouth is his destruction, and his lips are the snare of his soul." },
"07-19": { ref: "Proverbs 19:7", text: "All the brethren of the poor do hate him: how much more do his friends go far from him?" },
"07-20": { ref: "Exodus 20:7", text: "Thou shalt not take the name of the LORD thy God in vain..." },
"07-21": { ref: "Matthew 21:7", text: "And brought the ass, and the colt, and put on them their clothes, and they set him thereon." },
"07-22": { ref: "Proverbs 22:7", text: "The rich ruleth over the poor, and the borrower is servant to the lender." },
"07-23": { ref: "Psalm 23:7", text: "[Note: Psalm 23 only has 6 verses, so we default to verse 6] Surely goodness and mercy shall follow me all the days of my life..." },
"07-24": { ref: "Joshua 24:7", text: "And when they cried unto the LORD, he put darkness between you and the Egyptians..." },
"07-25": { ref: "Matthew 25:7", text: "Then all those virgins arose, and trimmed their lamps." },
"07-26": { ref: "Isaiah 26:7", text: "The way of the just is uprightness: thou, most upright, dost weigh the path of the just." },
"07-27": { ref: "Proverbs 27:7", text: "The full soul loatheth an honeycomb; but to the hungry soul every bitter thing is sweet." },
"07-28": { ref: "Deuteronomy 28:7", text: "The LORD shall cause thine enemies that rise up against thee to be smitten before thy face..." },
"07-29": { ref: "Jeremiah 29:7", text: "And seek the peace of the city whither I have caused you to be carried away captives..." },
"07-30": { ref: "Job 30:7", text: "Among the bushes they brayed; under the nettles they were gathered together." },
"07-31": { ref: "Proverbs 31:7", text: "Let him drink, and forget his poverty, and remember his misery no more." },
"08-01": { ref: "1 Peter 5:8", text: "Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about, seeking whom he may devour:" },
"08-02": { ref: "Exodus 5:8", text: "And the tale of the bricks, which they did make heretofore, ye shall lay upon them..." },
"08-03": { ref: "Amos 5:8", text: "Seek him that maketh the seven stars and Orion..." },
"08-04": { ref: "Philippians 4:8", text: "Whatsoever things are true, whatsoever things are honest... think on these things." },
"08-05": { ref: "Romans 5:8", text: "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us." },
"08-06": { ref: "Galatians 6:8", text: "For he that soweth to his flesh shall of the flesh reap corruption..." },
"08-07": { ref: "1 John 2:8", text: "Again, a new commandment I write unto you, which thing is true in him and in you..." },
"08-08": { ref: "Ephesians 2:8", text: "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God:" },
"08-09": { ref: "1 Samuel 2:9", text: "He will keep the feet of his saints, and the wicked shall be silent in darkness..." },
"08-10": { ref: "Titus 2:10", text: "Not purloining, but shewing all good fidelity..." },
"08-11": { ref: "Ephesians 2:11", text: "Wherefore remember, that ye being in time past Gentiles in the flesh..." },
"08-12": { ref: "1 Peter 2:12", text: "Having your conversation honest among the Gentiles..." },
"08-13": { ref: "Ephesians 2:13", text: "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ." },
"08-14": { ref: "1 Corinthians 13:8", text: "Charity never faileth: but whether there be prophecies, they shall fail..." },
"08-15": { ref: "Luke 2:15", text: "And it came to pass, as the angels were gone away from them into heaven..." },
"08-16": { ref: "2 Timothy 3:16", text: "All scripture is given by inspiration of God, and is profitable for doctrine..." },
"08-17": { ref: "Proverbs 17:8", text: "A gift is as a precious stone in the eyes of him that hath it..." },
"08-18": { ref: "Proverbs 18:8", text: "The words of a talebearer are as wounds, and they go down into the innermost parts of the belly." },
"08-19": { ref: "Proverbs 19:8", text: "He that getteth wisdom loveth his own soul..." },
"08-20": { ref: "Exodus 20:8", text: "Remember the sabbath day, to keep it holy." },
"08-21": { ref: "Matthew 21:8", text: "And a very great multitude spread their garments in the way..." },
"08-22": { ref: "Proverbs 22:8", text: "He that soweth iniquity shall reap vanity..." },
"08-23": { ref: "Psalm 23:6", text: "Surely goodness and mercy shall follow me all the days of my life..." }, 
"08-24": { ref: "Joshua 24:8", text: "And I brought you into the land of the Amorites, which dwelt on the other side Jordan..." },
"08-25": { ref: "Matthew 25:8", text: "And the foolish said unto the wise, Give us of your oil; for our lamps are gone out." },
"08-26": { ref: "Isaiah 26:8", text: "Yea, in the way of thy judgments, O LORD, have we waited for thee..." },
"08-27": { ref: "Proverbs 27:8", text: "As a bird that wandereth from her nest, so is a man that wandereth from his place." },
"08-28": { ref: "Deuteronomy 28:8", text: "The LORD shall command the blessing upon thee in thy storehouses..." },
"08-29": { ref: "Jeremiah 29:8", text: "For thus saith the LORD of hosts, the God of Israel; Let not your prophets and your diviners..." },
"08-30": { ref: "Job 30:8", text: "They were children of fools, yea, children of base men: they were viler than the earth." },
"08-31": { ref: "Proverbs 31:8", text: "Open thy mouth for the dumb in the cause of all such as are appointed to destruction." },
"09-01": { ref: "Genesis 9:1", text: "And God blessed Noah and his sons, and said unto them, Be fruitful, and multiply, and replenish the earth." },
"09-02": { ref: "Exodus 9:2", text: "For if thou refuse to let them go, and wilt hold them still," },
"09-03": { ref: "Amos 9:2", text: "Though they dig into hell, thence shall mine hand take them..." },
"09-04": { ref: "Philippians 4:9", text: "Those things, which ye have both learned, and received, and heard, and seen in me, do..." },
"09-05": { ref: "Romans 5:9", text: "Much more then, being now justified by his blood, we shall be saved from wrath through him." },
"09-06": { ref: "Galatians 6:9", text: "And let us not be weary in well doing: for in due season we shall reap, if we faint not." },
"09-07": { ref: "1 John 2:9", text: "He that saith he is in the light, and hateth his brother, is in darkness even until now." },
"09-08": { ref: "Ephesians 2:9", text: "Not of works, lest any man should boast." },
"09-09": { ref: "1 Samuel 2:9", text: "He will keep the feet of his saints, and the wicked shall be silent in darkness..." },
"09-10": { ref: "Titus 2:9", text: "Exhort servants to be obedient unto their own masters, and to please them well in all things..." },
"09-11": { ref: "Ephesians 2:11", text: "Wherefore remember, that ye being in time past Gentiles in the flesh..." },
"09-12": { ref: "1 Peter 2:12", text: "Having your conversation honest among the Gentiles..." },
"09-13": { ref: "Ephesians 2:13", text: "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ." },
"09-14": { ref: "1 Corinthians 13:9", text: "For we know in part, and we prophesy in part." },
"09-15": { ref: "Luke 2:15", text: "And it came to pass, as the angels were gone away from them into heaven..." },
"09-16": { ref: "2 Timothy 3:16", text: "All scripture is given by inspiration of God, and is profitable for doctrine..." },
"09-17": { ref: "Proverbs 17:9", text: "He that covereth a transgression seeketh love..." },
"09-18": { ref: "Proverbs 18:9", text: "He also that is slothful in his work is brother to him that is a great waster." },
"09-19": { ref: "Proverbs 19:9", text: "A false witness shall not be unpunished, and he that speaketh lies shall perish." },
"09-20": { ref: "Exodus 20:9", text: "Six days shalt thou labour, and do all thy work:" },
"09-21": { ref: "Matthew 21:9", text: "And the multitudes that went before, and that followed, cried, saying, Hosanna to the Son of David..." },
"09-22": { ref: "Proverbs 22:9", text: "He that hath a bountiful eye shall be blessed..." },
"09-23": { ref: "Psalm 23:6", text: "Surely goodness and mercy shall follow me all the days of my life..." },
"09-24": { ref: "Joshua 244:9", text: "Then Balak the son of Zippor, king of Moab, arose and warred against Israel..." },
"09-25": { ref: "Matthew 25:9", text: "But the wise answered, saying, Not so; lest there be not enough for us and you..." },
"09-26": { ref: "Isaiah 26:9", text: "With my soul have I desired thee in the night; yea, with my spirit within me will I seek thee early..." },
"09-27": { ref: "Proverbs 27:9", text: "Ointment and perfume rejoice the heart: so doth the sweetness of a man's friend by hearty counsel." },
"09-28": { ref: "Deuteronomy 28:9", text: "The LORD shall establish thee an holy people unto himself..." },
"09-29": { ref: "Jeremiah 29:9", text: "For they prophesy falsely unto you in my name: I have not sent them, saith the LORD." },
"09-30": { ref: "Job 30:9", text: "And now am I their song, yea, I am their byword." },
"10-01": { ref: "Genesis 10:1", text: "Now these are the generations of the sons of Noah..." },
"10-02": { ref: "Exodus 10:2", text: "And that thou mayest tell in the ears of thy son, and of thy son's son..." },
"10-03": { ref: "Amos 3:10", text: "For they know not to do right, saith the LORD..." },
"10-04": { ref: "Philippians 4:10", text: "But I rejoiced in the Lord greatly, that now at the last your care of me hath flourished again..." },
"10-05": { ref: "Romans 5:10", text: "For if, when we were enemies, we were reconciled to God by the death of his Son..." },
"10-06": { ref: "Galatians 6:10", text: "As we have therefore opportunity, let us do good unto all men..." },
"10-07": { ref: "1 John 2:10", text: "He that loveth his brother abideth in the light..." },
"10-08": { ref: "Ephesians 2:10", text: "For we are his workmanship, created in Christ Jesus unto good works..." },
"10-09": { ref: "1 Samuel 2:10", text: "The adversaries of the LORD shall be broken to pieces..." },
"10-10": { ref: "Titus 2:10", text: "Not purloining, but shewing all good fidelity..." },
"10-11": { ref: "Ephesians 2:11", text: "Wherefore remember, that ye being in time past Gentiles in the flesh..." },
"10-12": { ref: "1 Peter 2:12", text: "Having your conversation honest among the Gentiles..." },
"10-13": { ref: "Ephesians 2:13", text: "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ." },
"10-14": { ref: "1 Corinthians 13:10", text: "But when that which is perfect is come, then that which is in part shall be done away." },
"10-15": { ref: "Luke 2:15", text: "And it came to pass, as the angels were gone away from them into heaven..." },
"10-16": { ref: "2 Timothy 3:16", text: "All scripture is given by inspiration of God..." },
"10-17": { ref: "Proverbs 17:10", text: "A reproof entereth more into a wise man than an hundred stripes into a fool." },
"10-18": { ref: "Proverbs 18:10", text: "The name of the LORD is a strong tower: the righteous runneth into it, and is safe." },
"10-19": { ref: "Proverbs 19:10", text: "Delight is not seemly for a fool; much less for a servant to have rule over princes." },
"10-20": { ref: "Exodus 20:10", text: "But the seventh day is the sabbath of the LORD thy God..." },
"10-21": { ref: "Matthew 21:10", text: "And when he was come into Jerusalem, all the city was moved, saying, Who is this?" },
"10-22": { ref: "Proverbs 22:10", text: "Cast out the scorner, and contention shall go out..." },
"10-23": { ref: "Psalm 23:6", text: "Surely goodness and mercy shall follow me all the days of my life..." },
"10-24": { ref: "Joshua 24:10", text: "But I would not hearken unto Balaam; therefore he blessed you still..." },
"10-25": { ref: "Matthew 25:10", text: "And while they went to buy, the bridegroom came..." },
"10-26": { ref: "Isaiah 26:10", text: "Let favour be shewed to the wicked, yet will he not learn righteousness..." },
"10-27": { ref: "Proverbs 27:10", text: "Thine own friend, and thy father's friend, forsake not..." },
"10-28": { ref: "Deuteronomy 28:10", text: "And all people of the earth shall see that thou art called by the name of the LORD..." },
"10-29": { ref: "Jeremiah 29:10", text: "For thus saith the LORD, That after seventy years be accomplished at Babylon I will visit you..." },
"10-30": { ref: "Job 30:10", text: "They abhor me, they flee far from me..." },
"10-31": { ref: "Proverbs 31:10", text: "Who can find a virtuous woman? for her price is far above rubies." },
"11-01": { ref: "Genesis 11:1", text: "And the whole earth was of one language, and of one speech." },
"11-02": { ref: "Exodus 11:2", text: "Speak now in the ears of the people, and let every man borrow of his neighbour..." },
"11-03": { ref: "Amos 3:11", text: "Therefore thus saith the Lord GOD; An adversary there shall be even round about the land..." },
"11-04": { ref: "Philippians 4:11", text: "Not that I speak in respect of want: for I have learned, in whatsoever state I am..." },
"11-05": { ref: "Romans 5:11", text: "And not only so, but we also joy in God through our Lord Jesus Christ..." },
"11-06": { ref: "Galatians 6:11", text: "Ye see how large a letter I have written unto you with mine own hand." },
"11-07": { ref: "1 John 2:11", text: "But he that hateth his brother is in darkness, and walketh in darkness..." },
"11-08": { ref: "Ephesians 2:11", text: "Wherefore remember, that ye being in time past Gentiles in the flesh..." },
"11-09": { ref: "1 Samuel 2:11", text: "And Elkanah went to Ramah to his house. And the child did minister unto the LORD before Eli the priest." },
"11-10": { ref: "Titus 2:11", text: "For the grace of God that bringeth salvation hath appeared to all men," },
"11-11": { ref: "Ephesians 2:12", text: "That at that time ye were without Christ, being aliens from the commonwealth of Israel..." },
"11-12": { ref: "1 Peter 2:13", text: "Submit yourselves to every ordinance of man for the Lord's sake..." },
"11-13": { ref: "Ephesians 2:13", text: "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ." },
"11-14": { ref: "1 Corinthians 13:11", text: "When I was a child, I spake as a child, I understood as a child, I thought as a child..." },
"11-15": { ref: "Luke 2:15", text: "And it came to pass, as the angels were gone away from them into heaven..." },
"11-16": { ref: "2 Timothy 3:16", text: "All scripture is given by inspiration of God..." },
"11-17": { ref: "Proverbs 17:11", text: "An evil man seeketh only rebellion: therefore a cruel messenger shall be sent against him." },
"11-18": { ref: "Proverbs 18:11", text: "The rich man's wealth is his strong city, and as an high wall in his own conceit." },
"11-19": { ref: "Proverbs 19:11", text: "The discretion of a man deferreth his anger; and it is his glory to pass over a transgression." },
"11-20": { ref: "Exodus 20:11", text: "For in six days the LORD made heaven and earth, the sea, and all that in them is..." },
"11-21": { ref: "Matthew 21:11", text: "And the multitude said, This is Jesus the prophet of Nazareth of Galilee." },
"11-22": { ref: "Proverbs 22:11", text: "He that loveth pureness of heart, for the grace of his lips the king shall be his friend." },
"11-23": { ref: "Psalm 23:6", text: "Surely goodness and mercy shall follow me all the days of my life..." },
"11-24": { ref: "Joshua 24:11", text: "And ye went over Jordan, and came unto Jericho..." },
"11-25": { ref: "Matthew 25:11", text: "Afterward came also the other virgins, saying, Lord, Lord, open to us." },
"11-26": { ref: "Isaiah 26:11", text: "LORD, when thy hand is lifted up, they will not see..." },
"11-27": { ref: "Proverbs 27:11", text: "My son, be wise, and make my heart glad, that I may answer him that reproacheth me." },
"11-28": { ref: "Deuteronomy 28:11", text: "And the LORD shall make thee plenteous in goods..." },
"11-29": { ref: "Jeremiah 29:11", text: "For I know the thoughts that I think toward you, saith the LORD..." },
"11-30": { ref: "Job 30:11", text: "Because he hath loosed my cord, and afflicted me, they have also let loose the bridle before me." },
"12-01": { ref: "Genesis 12:1", text: "Now the LORD had said unto Abram, Get thee out of thy country..." },
"12-02": { ref: "Exodus 12:2", text: "This month shall be unto you the beginning of months..." },
"12-03": { ref: "Amos 3:12", text: "Thus saith the LORD; As the shepherd taketh out of the mouth of the lion two legs..." },
"12-04": { ref: "Philippians 4:12", text: "I know both how to be abased, and I know how to abound..." },
"12-05": { ref: "Romans 5:12", text: "Wherefore, as by one man sin entered into the world, and death by sin..." },
"12-06": { ref: "Galatians 6:12", text: "As many as desire to make a fair shew in the flesh, they constrain you to be circumcised..." },
"12-07": { ref: "1 John 2:12", text: "I write unto you, little children, because your sins are forgiven you for his name's sake." },
"12-08": { ref: "Ephesians 2:12", text: "That at that time ye were without Christ, being aliens from the commonwealth of Israel..." },
"12-09": { ref: "1 Samuel 2:12", text: "Now the sons of Eli were sons of Belial; they knew not the LORD." },
"12-10": { ref: "Titus 2:12", text: "Teaching us that, denying ungodliness and worldly lusts, we should live soberly, righteously..." },
"12-11": { ref: "Ephesians 2:13", text: "But now in Christ Jesus ye who sometimes were far off are made nigh by the blood of Christ." },
"12-12": { ref: "1 Peter 2:14", text: "Or unto governors, as unto them that are sent by him for the punishment of evildoers..." },
"12-13": { ref: "Ephesians 2:14", text: "For he is our peace, who hath made both one, and hath broken down the middle wall of partition..." },
"12-14": { ref: "1 Corinthians 13:12", text: "For now we see through a glass, darkly; but then face to face..." },
"12-15": { ref: "Luke 2:15", text: "And it came to pass, as the angels were gone away from them into heaven..." },
"12-16": { ref: "2 Timothy 3:16", text: "All scripture is given by inspiration of God, and is profitable for doctrine..." },
"12-17": { ref: "Proverbs 17:12", text: "Let a bear robbed of her whelps meet a man, rather than a fool in his folly." },
"12-18": { ref: "Proverbs 18:12", text: "Before destruction the heart of man is haughty, and before honour is humility." },
"12-19": { ref: "Proverbs 19:12", text: "The king's wrath is as the roaring of a lion; but his favour is as dew upon the grass." },
"12-20": { ref: "Exodus 20:12", text: "Honour thy father and thy mother: that thy days may be long upon the land..." },
"12-21": { ref: "Matthew 21:12", text: "And Jesus went into the temple of God, and cast out all them that sold and bought..." },
"12-22": { ref: "Proverbs 22:12", text: "The eyes of the LORD preserve knowledge, and he overthroweth the words of the transgressor." },
"12-23": { ref: "Psalm 23:6", text: "Surely goodness and mercy shall follow me all the days of my life..." },
"12-24": { ref: "Joshua 24:12", text: "And I sent the hornet before you, which drave them out from before you..." },
"12-25": { ref: "Matthew 1:21", text: "And she shall bring forth a son, and thou shalt call his name JESUS..." },
"12-26": { ref: "Isaiah 26:12", text: "LORD, thou wilt ordain peace for us: for thou also hast wrought all our works in us." },
"12-27": { ref: "Proverbs 27:12", text: "A prudent man foreseeth the evil, and hideth himself; but the simple pass on, and are punished." },
"12-28": { ref: "Deuteronomy 28:28", text: "The LORD shall smite thee with madness, and blindness, and astonishment of heart:" },
"12-29": { ref: "Psalm 29:11", text: "The LORD will give strength unto his people; the LORD will bless his people with peace." },
"12-30": { ref: "Job 30:30", text: "My skin is black upon me, and my bones are burned with heat." },
"12-31": { ref: "Ecclesiastes 12:13", text: "Let us hear the conclusion of the whole matter: Fear God, and keep his commandments: for this is the whole duty of man." }
};